
SELECT count(*),MOBILE_NO FROM 
dbo.CL_TREATMENT a
inner join dbo.CL_ORDER_TREATMENT b
on a.TREATMENT_ID=b.TREATMENT_ID
inner join dbo.CL_ORDER c
on b.ORDER_ID=c.ORDER_ID
group by c.MOBILE_NO

select count(*),BA_NO from 
dbo.CL_ORDER 
group by BA_NO
having count(*)>1

select count(*),ORDER_ID from 
dbo.CL_ORDER_TREATMENT 
group by ORDER_ID
having count(*)>1


SELECT MOBILE_NO,BA_NO,a.ORDER_ID,TREATMENT_ID,BATCH_ID FROM dbo.CL_ORDER_TREATMENT a
inner join dbo.CL_ORDER b
on a.ORDER_ID=b.ORDER_ID
where a.TREATMENT_ID=544

select * from dbo.CL_BATCH
where BATCH_ID=216

select MOBILE_NO,ACTION_STATUS,ACTION_STATUS_DTM,ACTION_REMARK,ORDER_ACTION_ID from dbo.CL_ORDER b
where MOBILE_NO='0800901088'

SELECT a.ORDER_ID,BA_NO,MOBILE_NO,TREATMENT_ID  FROM CL_ORDER_TREATMENT a  INNER JOIN dbo.CL_ORDER b  ON a.ORDER_ID=b.ORDER_ID  
WHERE MOBILE_NO = ('0800901088') -- and ORDER_ACTION_ID = (10) and ACTION_STATUS = (3)

SELECT TREATMENT_ID,count(BA_NO),BA_NO FROM dbo.CL_ORDER_TREATMENT a
inner join dbo.CL_ORDER b
on a.ORDER_ID=b.ORDER_ID
group by TREATMENT_ID
