select * from dbo.CL_BATCH
where BATCH_FILE_NAME='DMSRequest_20170213_180821.dat'

SELECT BATCH_ID  FROM dbo.CL_BATCH  WHERE BATCH_FILE_NAME = ('DMSRequest_20170213_180821.dat')  and INBOUND_STATUS = (1)

select * from CL_TREATMENT
where TREATMENT_ID in (

select TREATMENT_ID from CL_ORDER,CL_ORDER_TREATMENT
where CL_ORDER.ORDER_ID=CL_ORDER_TREATMENT.ORDER_ID
and BATCH_ID=547
and MOBILE_NO='0899010560'
)



/*Clear Data
UPDATE CL_ORDER
SET ACTION_STATUS=3
where BATCH_ID=547

update dbo.CL_BATCH
set INBOUND_STATUS=1
where BATCH_FILE_NAME='DMSRequest_20170213_180821.dat'
*/


SELECT * FROM dbo.PM_ADJ_REQUEST
GO
