delete from dbo.CL_AGENT_PERFORM
go
sp_chgattribute CL_AGENT_PERFORM, "identity_burn_max", 0, "0"
go 
delete from CL_AGENT_REGION
go
sp_chgattribute CL_AGENT_REGION, "identity_burn_max", 0, "0"
go
INSERT INTO dbo.CL_AGENT_PERFORM( PERFORM_ID, AGENT_ID, TEAM_ID, MANAGER_ID, SUPERVISOR_ID, DEBT_TYPE_ID, TOTAL_ASSIGN_ACC, TOTAL_ASSIGN_AMT, TOTAL_COLLECT_ACC, TOTAL_COLLECT_AMT, PERFORM_PCT_ACC, PERFORM_PCT_AMT, FORMULA_ID_AGT_ACC, FORMULA_ID_AGT_AMT, FORMULA_ID_SUP_ACC, FORMULA_ID_SUP_AMT, FORMULA_ID_MGR_ACC, FORMULA_ID_MGR_AMT, COMM_AGT_ACC, COMM_AGT_AMT, COMM_SUP_ACC, COMM_SUP_AMT, COMM_MGR_ACC, COMM_MGR_AMT, INCEN_AGT_ACC, INCEN_AGT_AMT, INCEN_SUP_ACC, INCEN_SUP_AMT, INCEN_MGR_ACC, INCEN_MGR_AMT, PROVINCE_EXP_AMT, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
select 111,AGENT_ID,1,1,1,1,50,500,50,500,50,500,1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5,6,99.99,getdate(),'Test',getdate(),'Test'
from CL_AGENT

update CL_HIS_BA_INVOICE_BALANCE
set INVOICE_TOTAL_BAL=2000,INVOICE_DISPUTE_BAL=2000


INSERT INTO dbo.CL_AGENT_REGION( AGENT_ID, REGION_ID, EFFECT_START_DATE, EFFECT_END_DATE, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 1, 1, getdate(),  getdate(),  getdate(), 'Test',  getdate(), 'Test')
INSERT INTO dbo.CL_AGENT_REGION( AGENT_ID, REGION_ID, EFFECT_START_DATE, EFFECT_END_DATE, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 2, 2, getdate(),  getdate(),  getdate(), 'Test',  getdate(), 'Test')
INSERT INTO dbo.CL_AGENT_REGION( AGENT_ID, REGION_ID, EFFECT_START_DATE, EFFECT_END_DATE, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 3, 3, getdate(),  getdate(),  getdate(), 'Test',  getdate(), 'Test')
GO
