--run script ALL_TABLES

delete from dbo.CL_JOB_TREATMENT
GO
delete from dbo.CL_JOB
GO
delete from CL_AGENT
delete from CL_AGENT_COMPANY
delete from CL_ASSIGN_JOB
delete from CL_ASSIGN
delete from CL_DEBT_TYPE
GO
sp_chgattribute CL_JOB, "identity_burn_max", 0, "0"
GO
sp_chgattribute CL_AGENT, "identity_burn_max", 0, "0"
GO
sp_chgattribute CL_AGENT_COMPANY, "identity_burn_max", 0, "0"
GO
sp_chgattribute CL_ASSIGN, "identity_burn_max", 0, "0"
GO
sp_chgattribute CL_DEBT_TYPE, "identity_burn_max", 0, "0"
GO
INSERT INTO dbo.CL_JOB(CA_NO,
 BA_NO,
 JOB_ACTION_ID,
 JOB_ASSIGN_CA,
 JOB_ASSIGN_BA,
 JOB_ASSIGN_AMT, 
JOB_MIN_DUE_DATE,
 JOB_ASSIGN_DATE,
 JOB_UNASSIGN_DATE,
 JOB_AGENT_ID,
 JOB_TEAM_ID,
 JOB_MANAGER_ID,
 JOB_SUPERVISOR_ID,
 JOB_DEBT_TYPE_ID,
 JOB_REGION_ID,
 JOB_STATUS,
 COMM_STATUS,
 INCEN_STATUS,
 ACTION_CRITERIA_ID, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
select distinct CA_NO,
BA_NO,
14,
1,
1,
1000.50,
getdate(),
getdate(),
dateadd(dd,30,getdate()),
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
getdate(),
'Test',
getdate(),
'Test'
 from dbo.CL_TREATMENT
 GO
 
insert into dbo.CL_JOB_TREATMENT
select min(TREATMENT_ID) TREATMENT_ID,
(select JOB_ID from dbo.CL_JOB J where T.BA_NO=J.BA_NO),getdate(),'TEST',getdate(),'TEST' from dbo.CL_TREATMENT T 
GROUP by T.BA_NO,T.CA_NO
GO


INSERT INTO dbo.CL_AGENT(AGENT_COMPANY_ID,AGENT_OWNER, AGENT_TYPE, AGENT_SUBTYPE, AGENT_CODE, AGENT_NAME,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY,AGENT_WORKDAY, AGENT_NOTIFY_BOO,EFFECT_START_DATE,AGENT_POSITION,AGENT_USERNAME) 
VALUES(1,1, 1, 1, 'AA', 'Agent A',  getdate(), 'Test', getdate(), 'Test',5,'Y',getdate(),1,'Agent A')
INSERT INTO dbo.CL_AGENT(AGENT_COMPANY_ID,AGENT_OWNER, AGENT_TYPE, AGENT_SUBTYPE, AGENT_CODE, AGENT_NAME,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY,AGENT_WORKDAY, AGENT_NOTIFY_BOO,EFFECT_START_DATE,AGENT_POSITION,AGENT_USERNAME) 
VALUES(2,1, 1, 1, 'AB', 'Agent B',  getdate(), 'Test', getdate(), 'Test',5,'Y',getdate(),1,'Agent B')
INSERT INTO dbo.CL_AGENT(AGENT_COMPANY_ID,AGENT_OWNER, AGENT_TYPE, AGENT_SUBTYPE, AGENT_CODE, AGENT_NAME,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY,AGENT_WORKDAY, AGENT_NOTIFY_BOO,EFFECT_START_DATE,AGENT_POSITION,AGENT_USERNAME) 
VALUES(3,1, 1, 1, 'AC', 'Agent C',  getdate(), 'Test', getdate(), 'Test',5,'Y',getdate(),1,'Agent C')
GO
INSERT INTO dbo.CL_AGENT_COMPANY(AGENT_COMPANY_CODE, AGENT_COMPANY_NAME ,SAP_COMP_CODE,SAP_COST_CENTER,OUTSOURCE_BOO,OUTSOURCE_VAT,EFFECT_START_DATE,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 'AC', 'Company A','AC' ,'AC','Y','Y',getdate(),getdate(), 'Test', getdate(), 'Test')
	INSERT INTO dbo.CL_AGENT_COMPANY(AGENT_COMPANY_CODE, AGENT_COMPANY_NAME ,SAP_COMP_CODE,SAP_COST_CENTER,OUTSOURCE_BOO,OUTSOURCE_VAT,EFFECT_START_DATE,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 'BC', 'Company B','AB' ,'AB','Y','Y',getdate(),getdate(), 'Test', getdate(), 'Test')
	INSERT INTO dbo.CL_AGENT_COMPANY(AGENT_COMPANY_CODE, AGENT_COMPANY_NAME ,SAP_COMP_CODE,SAP_COST_CENTER,OUTSOURCE_BOO,OUTSOURCE_VAT,EFFECT_START_DATE,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 'CC', 'Company C','AC' ,'AC','Y','Y',getdate(),getdate(), 'Test', getdate(), 'Test')
GO


update  CL_JOB
set JOB_AGENT_ID=1
where JOB_ID between 1 and 250

update  CL_JOB
set JOB_AGENT_ID=2
where JOB_ID between 251 and 500

update  CL_JOB
set JOB_AGENT_ID=3
where JOB_ID between 501 and 750


INSERT INTO dbo.CL_ASSIGN_JOB(ASSIGN_ID,JOB_ID, AGENT_ID, TEAM_ID, MANAGER_ID, SUPERVISOR_ID, MOVE_ASSIGN_ID, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
select JOB_ID,JOB_ID,1,1,1,1,1,getdate(),'Test',getdate(),'Test' from CL_JOB

update  CL_ASSIGN_JOB
set AGENT_ID=1
where JOB_ID between 1 and 250

update  CL_ASSIGN_JOB
set AGENT_ID=2
where JOB_ID between 251 and 500

update  CL_ASSIGN_JOB
set AGENT_ID=3
where JOB_ID between 501 and 750
GO

INSERT INTO dbo.CL_ASSIGN( ASSIGN_ACTION_ID, ASSIGN_CODE, ASSIGN_TYPE, ASSIGN_SUBTYPE, ASSIGN_METHOD, ASSIGN_REASON_ID, ASSIGN_START_DATE, ASSIGN_END_DATE, ASSIGN_STATUS, ACTION_CRITERIA_ID, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
select JOB_ID,'AA',1,1,1,1,getdate(),dateadd(day,30,getdate()),2,1,getdate(),'Test',getdate(),'Test'
from CL_JOB


update  CL_ASSIGN
set ASSIGN_CODE='AA'
where ASSIGN_ID between 1 and 250

update  CL_ASSIGN
set ASSIGN_CODE='AB'
where ASSIGN_ID between 251 and 500

update  CL_ASSIGN
set ASSIGN_CODE='AC'
where ASSIGN_ID between 501 and 750
GO


INSERT INTO dbo.CL_DEBT_TYPE( DEBT_TYPE_OWNER, DEBT_TYPE_MODE, DEBT_TYPE_CODE, DEBT_TYPE_NAME,FORMULA_ID_AGT_ACC,FORMULA_ID_AGT_AMT,FORMULA_ID_SUP_ACC,FORMULA_ID_SUP_AMT,FORMULA_ID_MGR_ACC,FORMULA_ID_MGR_AMT,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 1,1,'DA','DEBT A',1,1,1,1,1,1, getdate(), 'Test', getdate(), 'Test')
GO
INSERT INTO dbo.CL_DEBT_TYPE( DEBT_TYPE_OWNER, DEBT_TYPE_MODE, DEBT_TYPE_CODE, DEBT_TYPE_NAME,FORMULA_ID_AGT_ACC,FORMULA_ID_AGT_AMT,FORMULA_ID_SUP_ACC,FORMULA_ID_SUP_AMT,FORMULA_ID_MGR_ACC,FORMULA_ID_MGR_AMT,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 2,1,'DB','DEBT B',1,1,1,1,1,1, getdate(), 'Test', getdate(), 'Test')
GO
INSERT INTO dbo.CL_DEBT_TYPE( DEBT_TYPE_OWNER, DEBT_TYPE_MODE, DEBT_TYPE_CODE, DEBT_TYPE_NAME,FORMULA_ID_AGT_ACC,FORMULA_ID_AGT_AMT,FORMULA_ID_SUP_ACC,FORMULA_ID_SUP_AMT,FORMULA_ID_MGR_ACC,FORMULA_ID_MGR_AMT,CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 3,1,'DC','DEBT C',1,1,1,1,1,1, getdate(), 'Test', getdate(), 'Test')
GO

UPDATE CL_JOB
SET JOB_DEBT_TYPE_ID=1
where JOB_ID between 1 and 250


update  CL_JOB
set JOB_DEBT_TYPE_ID=2
where JOB_ID between 251 and 500

update  CL_JOB
set JOB_DEBT_TYPE_ID=3
where JOB_ID between 501 and 750

update CL_HIS_BA_ACCOUNT_BALANCE
set BALANCE_START_DATE=getdate(),MIN_INVOICE_DATE=getdate(),END_DAY_BOO='Y',DUE_TOTAL_BAL=1000,DUE_DISPUTE_BAL=100


update CL_BA_INFO
set SFF_ACCOUNT_ID='8a8d35b22408851601240f96cd4c02b8'


update CL_CA_INFO
set SFF_ACCOUNT_ID='8a8d35b22408851601240f96cd4c02b8'


update CL_BA_INFO
SET BILL_PROVINCE_ID=1,BILL_REGION_ID=1
where BA_NO between '30900000000003'  and '30900000000236'


update CL_BA_INFO
SET BILL_PROVINCE_ID=2,BILL_REGION_ID=2
where BA_NO between '30900000000236'  and '30900000001210'


update CL_BA_INFO
SET BILL_PROVINCE_ID=4,BILL_REGION_ID=3
where BA_NO between '30900000001210'  and '30900000001278'

update CL_BA_INFO
SET BILL_PROVINCE_ID=5,BILL_REGION_ID=8
where BA_NO between '30900000001279'  and '30900000001967'

update CL_BA_INFO
SET BILL_PROVINCE_ID=6,BILL_REGION_ID=4
where BA_NO between '30900000001971'  and '31400070063194'
