
SELECT CL_AGENT_COMPANY.AGENT_COMPANY_CODE||' : '||CL_AGENT_COMPANY.AGENT_COMPANY_NAME,CL_ASSIGN.ASSIGN_CODE,CL_REGION.REGION_CODE||'('||CL_REGION.REGION_NAME||')',CL_PROVINCE.PROVINCE_CODE||'('||CL_PROVINCE.PROVINCE_NAME||')',
PM_COMPANY.COMPANY_CODE,CL_BA_INFO.BA_NO,CL_CA_INFO.CA_NO,CL_CA_INFO.CA_NAME,CL_MOBILE_INFO.MOBILE_NO,CL_SFF_MOBILE_STATUS.MOBILE_STATUS,
CL_CA_INFO.TAX_ID_NUMBER,CL_BA_INFO.BILL_ADDRESS_NAME||' '||CL_BA_INFO.BILL_ADDRESS_LINE_1||' '||CL_BA_INFO.BILL_ADDRESS_LINE_2||' '||
CL_BA_INFO.BILL_ADDRESS_LINE_3||' '||CL_BA_INFO.BILL_ADDRESS_LINE_4||' '||CL_BA_INFO.BILL_ADDRESS_LINE_5 CL_BA_INFO_ADDRESS,
CL_BA_INFO.BILL_ZIPCODE,SFF_ACCOUNT.CONTACT_MOBILE_PHONE BA_CONTACT_MOBILE_PHONE,CL_CA_INFO.VAT_ADDRESS_NAME||' '||
CL_CA_INFO.VAT_ADDRESS_LINE_1||' '||CL_CA_INFO.VAT_ADDRESS_LINE_2||' '||CL_CA_INFO.VAT_ADDRESS_LINE_3||' '||
CL_CA_INFO.VAT_ADDRESS_LINE_4||' '||CL_CA_INFO.VAT_ADDRESS_LINE_5,CL_CA_INFO.VAT_ZIPCODE,
SFF_ACCOUNT.CONTACT_MOBILE_PHONE CA_CONTACT_MOBILE_PHONE,PM_INVOICE.INVOICE_NUM,
convert(char(10),CL_HIS_BA_ACCOUNT_BALANCE.MIN_INVOICE_DATE,103)|| '-'|| convert(char(10),CL_HIS_BA_ACCOUNT_BALANCE.MAX_INVOICE_DATE,103) BILL_CYCLE,
CL_BA_INFO.REGISTER_DATE,CL_HIS_BA_INVOICE_BALANCE.INVOICE_TOTAL_BAL,CL_HIS_BA_INVOICE_BALANCE.MOVE_TOTAL_AMT,CL_HIS_BA_INVOICE_BALANCE.INVOICE_TOTAL_BAL
FROM CL_BA_INFO CL_BA_INFO
LEFT JOIN CL_REGION CL_REGION 
ON CL_BA_INFO.BILL_REGION_ID=CL_REGION.REGION_ID
LEFT JOIN CL_PROVINCE CL_PROVINCE
ON CL_BA_INFO.BILL_PROVINCE_ID=CL_PROVINCE.PROVINCE_ID
LEFT JOIN PMDB..PM_COMPANY PM_COMPANY
ON CL_BA_INFO.COMPANY_CODE=PM_COMPANY.COMPANY_ABBR
INNER JOIN CL_JOB CL_JOB
ON CL_BA_INFO.BA_NO=CL_JOB.BA_NO
INNER JOIN CL_CA_INFO CL_CA_INFO
ON CL_JOB.CA_NO=CL_CA_INFO.CA_NO
LEFT JOIN CL_MOBILE_INFO CL_MOBILE_INFO
ON CL_MOBILE_INFO.BA_NO=CL_BA_INFO.BA_NO
LEFT JOIN CL_SFF_MOBILE_STATUS CL_SFF_MOBILE_STATUS
ON CL_SFF_MOBILE_STATUS.MOBILE_STATUS=CL_MOBILE_INFO.MOBILE_STATUS
INNER JOIN CPDB..SFF_ACCOUNT SFF_ACCOUNT
ON SFF_ACCOUNT.ROW_ID=CL_BA_INFO.SFF_ACCOUNT_ID
INNER JOIN CPDB..SFF_ACCOUNT  NEW_SFF_ACCOUNT
ON NEW_SFF_ACCOUNT.ROW_ID=CL_CA_INFO.SFF_ACCOUNT_ID 
INNER JOIN CL_HIS_BA_INVOICE_BALANCE CL_HIS_BA_INVOICE_BALANCE
ON CL_HIS_BA_INVOICE_BALANCE.BA_NO=CL_BA_INFO.BA_NO
INNER JOIN PMDB..PM_INVOICE PM_INVOICE
ON PM_INVOICE.INVOICE_ID=CL_HIS_BA_INVOICE_BALANCE.INVOICE_ID 
INNER JOIN CL_HIS_BA_ACCOUNT_BALANCE CL_HIS_BA_ACCOUNT_BALANCE
ON CL_HIS_BA_ACCOUNT_BALANCE.BA_NO=CL_JOB.BA_NO
INNER JOIN CL_AGENT CL_AGENT
ON CL_AGENT.AGENT_ID=CL_JOB.JOB_AGENT_ID
INNER JOIN CL_AGENT_COMPANY CL_AGENT_COMPANY
ON CL_AGENT_COMPANY.AGENT_COMPANY_CODE=CL_AGENT.AGENT_CODE
INNER JOIN CL_ASSIGN CL_ASSIGN
ON CL_ASSIGN.ASSIGN_ACTION_ID=CL_JOB.JOB_ACTION_ID
where CL_BA_INFO.BA_NO='30900000000186'

/*
select * FROM CL_JOB

INSERT INTO dbo.CL_ASSIGN( ASSIGN_ACTION_ID, ASSIGN_CODE, ASSIGN_TYPE, ASSIGN_SUBTYPE, ASSIGN_METHOD, ASSIGN_REASON_ID, ASSIGN_START_DATE, ASSIGN_END_DATE, ASSIGN_STATUS, ACTION_CRITERIA_ID, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 1, 'SUS', 0, 0, 0, 0, '2017-2-13', '2017-2-13', 0, 0, '2017-2-13 2:37:33', '', '2017-2-13 2:37:33', '')
GO

INSERT INTO dbo.CL_AGENT_COMPANY(AGENT_COMPANY_CODE, AGENT_COMPANY_NAME, AGENT_COMPANY_TAXID, AGENT_COMPANY_EMAIL, AGENT_COMPANY_MOBILE, AGENT_COMPANY_PHONE, AGENT_COMPANY_FAX, AGENT_COMPANY_ADDRESS, AGENT_COMPANY_CONTACT, SAP_COMP_CODE, SAP_COST_CENTER, OUTSOURCE_BOO, OUTSOURCE_VAT, EFFECT_START_DATE, EFFECT_END_DATE, RECORD_ORDER, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES('Test Test', 'Test Company name', 'AGENT_COMPANY_TAXID', 'a@a.com', '0823745678', '0823745678', '', '', '', '', '', '', '', '2017-2-13', '2017-2-13', 0, '2017-2-13 2:31:11', '', '2017-2-13 2:31:11', '')
GO
OUTSOURCE_BOO = 'Y'
UPDATE CL_JOB
set JOB_ACTION_ID=1

select * FROM CL_HIS_BA_ACCOUNT_BALANCE
WHERE BA_NO='30900000000186'

update CL_HIS_BA_ACCOUNT_BALANCE
set INVOICE_ID=46889

select * from CL_MOBILE_INFO
where BA_NO='30900000000049'


select * from CL_HIS_BA_INVOICE_BALANCE

INSERT INTO dbo.CL_HIS_BA_INVOICE_BALANCE( AR_MOVEMENT_ID, BA_NO, INVOICE_ID, PROCESS_DTM, MOVEMENT_DATE, MOVEMENT_SEQ, MOVEMENT_TYPE, MOVEMENT_FLG, REF_DOC_TYPE, REF_DOC_ID, REF_DOC_DATE, MOVE_NON_VAT_AMT, MOVE_EXC_VAT_AMT, MOVE_VAT_AMT, MOVE_TOTAL_AMT, INVOICE_NON_VAT_BAL, INVOICE_EXC_VAT_BAL, INVOICE_VAT_BAL, INVOICE_TOTAL_BAL, INVOICE_DISPUTE_BAL, BACKDATE_START_DATE, BACKDATE_END_DATE, BALANCE_START_DATE, BALANCE_END_DATE, RECORD_START_DTM, RECORD_END_DTM, END_DAY_BOO, CURRENT_BOO, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY) 
	VALUES( 1, '30900000000186', 0, '2017-2-13 2:10:1', '2017-2-13', 0, '', '', '', 0, '2017-2-13', 0, 0, 0, 0, 0, 0, 0, 0, 0, '2017-2-13', '2017-2-13', '2017-2-13', '2017-2-13', '2017-2-13 2:10:1', '2017-2-13 2:10:1', '', '', '2017-2-13 2:10:1', '', '2017-2-13 2:10:1', '')
GO



select CL_CA_INFO.SFF_ACCOUNT_ID,CL_BA_INFO.SFF_ACCOUNT_ID,BA_NO,CL_BA_INFO.CA_NO,SFF_ACCOUNT.CONTACT_MOBILE_PHONE,CL_BA_INFO.SFF_ACCOUNT_ID,NEW_SFF_ACCOUNT.CONTACT_MOBILE_PHONE ,SFF_ACCOUNT.CONTACT_MOBILE_PHONE from CL_BA_INFO CL_BA_INFO
inner join CL_CA_INFO CL_CA_INFO
on CL_CA_INFO.CA_NO=CL_BA_INFO.CA_NO
inner join CPDB..SFF_ACCOUNT SFF_ACCOUNT
on SFF_ACCOUNT.ROW_ID=CL_CA_INFO.SFF_ACCOUNT_ID
inner join CPDB..SFF_ACCOUNT NEW_SFF_ACCOUNT
on NEW_SFF_ACCOUNT.ROW_ID=CL_BA_INFO.SFF_ACCOUNT_ID
where BA_NO='30900000000186'


UPDATE CPDB..SFF_ACCOUNT
SET CONTACT_MOBILE_PHONE='0812345678'
where ROW_ID='8a8d35b22413b80a01242d82dc6a0cb0'


select SFF_ACCOUNT_ID,CONTACT_MOBILE_PHONE from CPDB..SFF_ACCOUNT SFF_ACCOUNT
where CONTACT_MOBILE_PHONE='0819552524'

select BA_NO,CL_BA_INFO.CA_NO from CL_BA_INFO INNER JOIN CL_CA_INFO
ON CL_BA_INFO.CA_NO=CL_CA_INFO.CA_NO
where CL_BA_INFO.SFF_ACCOUNT_ID in  (
select ROW_ID from CPDB..SFF_ACCOUNT SFF_ACCOUNT
where CONTACT_MOBILE_PHONE is not null)
and CL_CA_INFO.SFF_ACCOUNT_ID in  (
select ROW_ID from CPDB..SFF_ACCOUNT SFF_ACCOUNT
where CONTACT_MOBILE_PHONE is not null)

SELECT SFF_ACCOUNT_ID FROM CL_CA_INFO
where CA_NO='30900000000047'

select * from CPDB..SFF_ACCOUNT
where ROW_ID='8a8d35b224088516012413485d0606fe'

UPDATE CL_JOB
SET BA_NO='30900000000186',CA_NO='30900000000185'
*/