SELECT
GC.AGENT_COMPANY_CODE AS PARTY_CODE,
GC.AGENT_COMPANY_CODE ||' ('|| GC.AGENT_COMPANY_NAME ||')' AS PARTY_NAME,
A.ASSIGN_CODE AS ASSIGN_NO,
R.REGION_CODE AS BILL_REGION,
R.REGION_CODE ||' ('|| R.REGION_NAME || ')' AS BILL_REGION_NAME,
P.PROVINCE_CODE AS PROVINCE_CODE,
P.PROVINCE_CODE ||' ('|| P.PROVINCE_NAME ||')' AS PROVINCE_NAME,
J.JOB_ASSIGN_DATE AS ASSIGN_DATE,
J.JOB_UNASSIGN_DATE AS UNASSIGN_DATE,
B.COMPANY_CODE,
B.BA_NO,
B.CA_NO,
C.CA_NAME,
CASE WHEN B.BA_STATUS = 'Active' THEN RMACT.MOBILE_NO  ELSE RMALL.MOBILE_NO  END AS REF_MOBILE_NO,
CASE WHEN B.BA_STATUS = 'Active' THEN RMACT.MOBILE_STATUS ELSE RMALL.MOBILE_STATUS  END AS REF_MOBILE_STATUS,

C.TAX_ID_NUMBER AS ID_CARD,

RTRIM(LTRIM(B.BILL_ADDRESS_LINE_1 ||' '|| B.BILL_ADDRESS_LINE_2 ||' '|| B.BILL_ADDRESS_LINE_3 ||' '|| B.BILL_ADDRESS_LINE_4 ||' '|| B.BILL_ADDRESS_LINE_5)) AS BILL_ADDRESS,
B.BILL_ZIPCODE,

(SELECT S1.CONTACT_MOBILE_PHONE FROM CPDB.dbo.SFF_ACCOUNT S1 WHERE S1.ROW_ID = B.SFF_ACCOUNT_ID) AS BA_CONTACT_TEL, 

RTRIM(LTRIM(C.VAT_ADDRESS_LINE_1 ||' '|| C.VAT_ADDRESS_LINE_2 ||' '|| C.VAT_ADDRESS_LINE_3 ||' '|| C.VAT_ADDRESS_LINE_4 ||' '|| C.VAT_ADDRESS_LINE_5)) AS HOME_ADDRESS,
C.VAT_ZIPCODE AS HOME_ZIPCODE,

(SELECT S1.CONTACT_MOBILE_PHONE FROM CPDB.dbo.SFF_ACCOUNT S1 WHERE S1.ROW_ID = C.SFF_ACCOUNT_ID) AS CA_CONTACT_TEL
FROM CL_JOB J 
JOIN CL_JOB_TREATMENT JT ON J.JOB_ID = JT.JOB_ID AND J.JOB_STATUS = 1 -- Assigned
               AND EXISTS (SELECT * FROM CL_ACTION AC WHERE AC.ACTION_ID = J.JOB_ACTION_ID AND AC.ACTION_MODE = 6) -- Third Party 
JOIN CL_TREATMENT T ON JT.TREATMENT_ID = T.TREATMENT_ID
JOIN CL_AGENT G ON J.JOB_AGENT_ID = G.AGENT_ID
JOIN CL_AGENT_COMPANY GC ON G.AGENT_COMPANY_ID = GC.AGENT_COMPANY_ID
JOIN CL_ASSIGN_JOB AJ ON J.JOB_ID = AJ.JOB_ID
JOIN CL_ASSIGN A ON AJ.ASSIGN_ID = A.ASSIGN_ID AND A.ASSIGN_STATUS = 2 --  Confirmed
JOIN CL_BA_INFO B ON T.BA_NO = B.BA_NO
JOIN CL_CA_INFO C ON T.CA_NO = C.CA_NO
JOIN CL_REGION R ON B.BILL_REGION_ID = R.REGION_ID
JOIN CL_PROVINCE P ON B.BILL_PROVINCE_ID = P.PROVINCE_ID
JOIN (SELECT M.MOBILE_NO,M.BA_NO,M.MOBILE_STATUS
        FROM CL_MOBILE_INFO M
        WHERE MOBILE_STATUS_DTM = (SELECT MAX(M2.MOBILE_STATUS_DTM)
                                                         FROM CL_MOBILE_INFO M2
                                                         WHERE M2.BA_NO = M.BA_NO AND ( M2.MOBILE_STATUS = 'Active' OR M2.MOBILE_STATUS LIKE 'Suspend%' ) )
) AS RMACT on J.BA_NO=RMACT.BA_NO
JOIN (SELECT M.MOBILE_NO,M.BA_NO,M.MOBILE_STATUS
        FROM CL_MOBILE_INFO M
        WHERE MOBILE_STATUS_DTM = (SELECT MAX(M2.MOBILE_STATUS_DTM)
                                                         FROM CL_MOBILE_INFO M2
                                                         WHERE M2.BA_NO = M.BA_NO)
) AS RMALL on J.BA_NO=RMALL.BA_NO
WHERE ( J.JOB_ASSIGN_DATE >= '2017-02-25' AND J.JOB_ASSIGN_DATE <= current_date() ) -- Criteria จากหน้าจอ (Mandatory)
//AND B.COMPANY_CODE = 'AIS' -- Criteria จากหน้าจอ เช่น AIS, AWN, AIR, SBN, DPC (Optional)
//AND A.ASSIGN_CODE = 'AC' -- Criteria จากหน้าจอ เช่น 59010001, 60020056  (Optional)
//AND GC.AGENT_COMPANY_CODE || R.REGION_CODE = 'CCCN' -- Criteria จากหน้าจอ เช่น ARNCB (ARN = AGENT_COMPANY_CODE, CB = REGION_CODE) (Optional)
ORDER BY GC.AGENT_COMPANY_CODE ||' ('|| GC.AGENT_COMPANY_NAME ||')',A.ASSIGN_CODE,R.REGION_CODE ||' ('|| R.REGION_NAME || ')',P.PROVINCE_CODE ||' ('|| P.PROVINCE_NAME ||')',J.JOB_ASSIGN_DATE ,J.JOB_UNASSIGN_DATE,B.COMPANY_CODE,
B.BA_NO
