SELECT 
I.INVOICE_NUM AS INVOICE_NO,
CONVERT(CHAR(10),I.BILL_START_DATE,103) ||' - '|| CONVERT(CHAR(10),I.BILL_END_DATE,103) AS BILL_CYCLE,
(SELECT B.REGISTER_DATE FROM CL_BA_INFO B WHERE B.BA_NO = IB.BA_NO) AS BA_REGISTER_DATE,
(IB.INVOICE_TOTAL_BAL - IB.INVOICE_DISPUTE_BAL) AS ASSIGN_AMT,
((IB.INVOICE_TOTAL_BAL - IB.INVOICE_DISPUTE_BAL) - (I.INVOICE_TOTAL_BAL - I.PENDING_DISPUTE_AMT)) AS PAID_AMOUNT,
(I.INVOICE_TOTAL_BAL - I.PENDING_DISPUTE_AMT) AS INVOICE_BALANCE
FROM PMDB.dbo.PM_INVOICE I
JOIN CL_HIS_BA_INVOICE_BALANCE IB ON I.INVOICE_ID = IB.INVOICE_ID
WHERE 1=1
//AND IB.BA_NO = '30900000000400' -- BA No จากด้านบน
AND IB.RECORD_END_DTM IS NULL  /*รายการที่ยังมีผลใช้งานอยู่ */
AND IB.END_DAY_BOO = 'Y' /*รายการ Balance สุดท้ายของวัน*/
AND (IB.INVOICE_TOTAL_BAL - IB.INVOICE_DISPUTE_BAL) > 0  /* Invoice ที่มีหนี้ค้างชำระอยู่ ณ วันที่ Assign (หักยอด Dispute Pending ออกเสมอ )*/
AND I.PAYMENT_DUE_DATE < '2017-02-25'   /*เฉพาะ Invoice ที่เกินกำหนดชำระแล้ว */   /* --> ขอเพิ่ม Condition นี้นะคะ */
AND '2017-02-25' BETWEEN IB.BALANCE_START_DATE AND ISNULL(IB.BALANCE_END_DATE, CURRENT_DATE())  /*Invoice ที่มีหนี้ค้างชำระอยู่ ณ วันที่  */