SET IDENTITY_INSERT dbo.CL_RANGE ON
insert into dbo.CL_RANGE (RANGE_ID, RANGE_TYPE, RANGE_NAME, RANGE_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (1, 1, 'Aging Report Template 15', 'Template ID 2222', 0, 1, '20170301 00:00:00', 'Migration', '20040909 10:31:59', 'micsr')
insert into dbo.CL_RANGE (RANGE_ID, RANGE_TYPE, RANGE_NAME, RANGE_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (2, 1, 'Aging Report Template 30', null, 0, 1, '20170301 00:00:00', 'CPAC', null, null)
insert into dbo.CL_RANGE (RANGE_ID, RANGE_TYPE, RANGE_NAME, RANGE_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (3, 2, 'Statement Report Template', 'Template ID 1222', 0, 1, '20170301 00:00:00', 'Migration', '20040909 10:31:59', 'micsr')
insert into dbo.CL_RANGE (RANGE_ID, RANGE_TYPE, RANGE_NAME, RANGE_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (4, 1, 'Debt Age Range (Corporate)', null, 0, 1, '20170301 00:00:00', 'CPAC', null, null)
insert into dbo.CL_RANGE (RANGE_ID, RANGE_TYPE, RANGE_NAME, RANGE_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (5, 1, 'Debt Age Range (Account)', null, 0, 1, '20170301 00:00:00', 'CPAC', null, null)
SET IDENTITY_INSERT dbo.CL_RANGE OFF