SET IDENTITY_INSERT dbo.CL_EXECUTION_METHOD ON
insert into dbo.CL_EXECUTION_METHOD (EXECUTION_METHOD_ID, EXECUTION_METHOD_CODE, EXECUTION_METHOD_NAME, EXECUTION_METHOD_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (1, '1001', 'บังคับคดีให้ยึดทรัพย์', null, 1, 1, '20170301 00:00:00', 'Migration', '20050613 10:34:29', 'sombatna')
insert into dbo.CL_EXECUTION_METHOD (EXECUTION_METHOD_ID, EXECUTION_METHOD_CODE, EXECUTION_METHOD_NAME, EXECUTION_METHOD_DESC, RECORD_ORDER, RECORD_STATUS, CREATED, CREATED_BY, LAST_UPD, LAST_UPD_BY)
values (2, '1002', 'ผ่อนชำระ', null, 2, 1, '20170301 00:00:00', 'Migration', '20160627 10:47:04', 'duanpens')
SET IDENTITY_INSERT dbo.CL_EXECUTION_METHOD OFF