SELECT BA_NO,ACTION_STATUS,ACTION_STATUS_DTM,ACTION_REMARK,SFF_BLACKLIST_ID FROM dbo.CL_BLACKLIST
where BATCH_ID in (10) 

select BA_NO,ACTION_STATUS,ACTION_STATUS_DTM,ACTION_REMARK,ACTION_ID from dbo.CL_TREATMENT
where TREATMENT_ID in (
SELECT TREATMENT_ID FROM dbo.CL_BLACKLIST a ,dbo.CL_BLACKLIST_TREATMENT b
where a.BLACKLIST_ID=b.BLACKLIST_ID
and BATCH_ID in (10))




SELECT * FROM CL_BA_INFO
where BA_NO='30900000000188'

select * from dbo.CL_BATCH
WHERE  BATCH_ID in (4,10)
select * from dbo.CL_BATCH
where BATCH_FILE_NAME='AccountDebtBlacklist_20170307_215234.dat'

20170307000000

update dbo.CL_BATCH
set INBOUND_STATUS=1,RESPONSE_FILE_NAME=null

update dbo.CL_BLACKLIST
set ACTION_STATUS=3,SFF_BLACKLIST_ID=null,ACTION_REMARK=null

update dbo.CL_TREATMENT
set ACTION_STATUS=3,ACTION_REMARK=null,ACTION_ID=30


select * FROM CPDB.dbo.SFF_BLACKLIST

update  CPDB.dbo.SFF_BLACKLIST
SET BLACKLIST_END_DT=BLACKLIST_START_DT


 SELECT C.BLACKLIST_ID,ROW_ID  FROM CL_BLACKLIST C, CPDB..SFF_BLACKLIST S 
 WHERE C.BLACKLIST_OPTION = 2  AND C.BLACKLIST_TYPE = S.BLACKLIST_TYPE  
AND C.BLACKLIST_SUBTYPE = S.BLACKLIST_SUBTYPE  AND C.BLACKLIST_SOURCE = S.BLACKLIST_SOURCE  
AND C.BLACKLIST_REQUEST_DATE = S.BLACKLIST_END_DT  
AND ACTION_STATUS = (3) AND BATCH_ID = (10) 
AND S.BILLING_ACCNT_ID = (SELECT B.SFF_ACCOUNT_ID FROM CL_BA_INFO B WHERE B.BA_NO = '30900000001151') 
 AND C.BA_NO = '30900000001151'  
AND convert(Varchar(10),C.BLACKLIST_REQUEST_DATE,112)+ str_replace(convert(Varchar(15),BLACKLIST_REQUEST_DATE,108),':',null) = '' 
 AND C.BLACKLIST_TYPE = 'BLACKLIST_TYPE-05'  AND C.BLACKLIST_SUBTYPE = 'BLACKLIST_SUBTYPE-05'  AND C.BLACKLIST_SOURCE = 'AIS'  AND C.BLACKLIST_REASON = '' 


SELECT C.BLACKLIST_ID,ROW_ID  FROM CL_BLACKLIST C, CPDB..SFF_BLACKLIST S  WHERE C.BLACKLIST_OPTION = 2  AND C.BLACKLIST_TYPE = S.BLACKLIST_TYPE  AND C.BLACKLIST_SUBTYPE = S.BLACKLIST_SUBTYPE  AND C.BLACKLIST_SOURCE = S.BLACKLIST_SOURCE  AND C.BLACKLIST_REQUEST_DATE = S.BLACKLIST_END_DT  AND ACTION_STATUS = (3) AND BATCH_ID = (10) AND S.BILLING_ACCNT_ID = (SELECT B.SFF_ACCOUNT_ID FROM CL_BA_INFO B WHERE B.BA_NO = '30900000001151')  AND C.BA_NO = '30900000001151'  AND convert(Varchar(10),C.BLACKLIST_REQUEST_DATE,112)+ str_replace(convert(Varchar(15),BLACKLIST_REQUEST_DATE,108),':',null) = '20170307000000'  AND C.BLACKLIST_TYPE = 'BLACKLIST_TYPE-05'  AND C.BLACKLIST_SUBTYPE = 'BLACKLIST_SUBTYPE-05'  AND C.BLACKLIST_SOURCE = 'AIS'  AND C.BLACKLIST_REASON = 'BLACKLIST_REASON-05'


update CL_BLACKLIST
set BLACKLIST_OPTION=2

select * from dbo.CL_BLACKLIST
where BATCH_ID=10

select * from dbo.CL_ACTION
where ACTION_MODE in (10,11)