CREATE PROCEDURE SP_GET_TOP_SUPER_DEAL_FLAG
(
    @BA_NO varchar(30)
)
as
begin
SELECT TOP 1 CASE WHEN SC.PROJECT_NAME LIKE '%Super Deal%' THEN 'Y' ELSE 'N' END,M.BA_NO
FROM CPDB.dbo.SFF_CONTRACT SC, CL_MOBILE_INFO M
WHERE SC.ASSET_ID = M.SFF_ASSET_INSTANCE_ID
AND M.BA_NO = @BA_NO
AND SC.STATUS_CD <> 'Deleted'
ORDER BY START_DT DESC
end

go
create existing table RPC_GET_TOP_SUPER_DEAL_FLAG
(
    SUPER_DEAL_FLAG nvarchar(30),
    BA_NO varchar(30)
)
external procedure

at "loopback.CLDB.dbo.SP_GET_TOP_SUPER_DEAL_FLAG"
go
